### PR TITLE
NFT: Check that datum id correspond to NFT

### LINKED ISSUE #230: NFT: Validator Check - the Datum and the Token correspond to one another.
- Check that the Datum and the Token correspond to one another when sending back i.e.
```
in   : utxo (Token A + Valid Datum A)
out : utxo1 (Token A + Valid Datum A) + utxo2 (Token B + Valid Datum B)
```
Case in which it fails:
```
in   : utxo (Token A + Valid Datum A)
out : utxo1 (Token A + Valid Datum B) + utxo2 (Token B + Valid Datum A)
```
https://github.com/mlabs-haskell/plutus-use-cases/blob/76099301ef253f427ec72eafbf99b1e559766848/mlabs/src/Mlabs/NFT/Validation.hs#L118

- [ ] add logic
- [ ] add tests

### PR DESCRIPTION
**Pull request by t4ccer**
Close #230

### CODE REVIEW

File: mlabs/src/Mlabs/NFT/Validation.hs [hunk 1]
```diff
@@ -459,10 +475,16 @@ getInputDatums ctx =
...
-getOutputDatums ctx =
-  mapMaybe (PlutusTx.fromBuiltinData . getDatum)
-    . mapMaybe (\hash -> findDatum hash $ scriptContextTxInfo ctx)
-    . mapMaybe txOutDatumHash
+getOutputDatums = fmap fst . getOutputDatumsWithTx
+
+{-# INLINEABLE getOutputDatumsWithTx #-}
+
+-- | Returns datums and coresponding UTXOs attached to outputs of transaction
+getOutputDatumsWithTx :: PlutusTx.FromData a => ScriptContext -> [(a, TxOut)]
```
Comment (cstml) [inline mlabs/src/Mlabs/NFT/Validation.hs:483]: This is a much better way. Can we implement a similar utility/check for the inputs?

**Review by cstml — APPROVED** [review]
